# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class ApiFunction:
        name: str
        type: str
        url: str
    class App:
        name: str
        stage: str
    class AuthFunction:
        name: str
        type: str
        url: str
    class TestFunction:
        name: str
        type: str
        url: str
    class WorkerFunction:
        name: str
        type: str

