# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class ApiService:
        name: str
        type: str
        url: str
    class App:
        name: str
        stage: str
    class AuthService:
        name: str
        type: str
        url: str
    class WorkerService:
        name: str
        type: str

